 CREATE TABLE "C##RABBIT2"."BOARD" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE), 
	"SUBJECT" VARCHAR2(20 BYTE), 
	"MEMO" NCLOB, 
	"COUNT" NUMBER, 
	"REGIDATE" TIMESTAMP (6), 
	 CONSTRAINT "BOARD_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("MEMO") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##RABBIT2"."BOARD_TRG" 
BEFORE INSERT ON BOARD 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##RABBIT2"."BOARD_TRG" ENABLE;

/* 데이터 추가 */
INSERT INTO "C##RABBIT2"."BOARD" (NAME, subject, memo, count, regidate) VALUES ('홍길동', '안녕하세요.', '메모메모', '0', '2020-09-29 11:11:00');

/* 데이터 등록 후 커밋할 것(대량 정보 처리 후) */
COMMIT;

/* 성능 실험 */
select * from board order by id + 1;
select rownum rn, id, name, subject, memo, count, regidate from board where id > 0;
select rownum rn, id, name, subject, memo, count, regidate from board order by id desc;

/* 전체 게시글 갯수 조회 */
select count(*) from board;

/* 페이징 특정 구역 처리 */
select *
from (select /*+INDEX_DESC(tbl_board pk_board) */ rownum rn, A.*
	 from board A order by id desc)
where rn >= 10 and rn <= 20;

/* 페이징 특정 구역 처리(검색) */
select *
from (select /*+INDEX_DESC(tbl_board pk_board) */ rownum rn, A.*
	 from board A where subject like '%친%' order by id desc)
where rn >= 10 and rn <= 20;

/* 특정 게시글 갯수 조회(검색) */
select count(*) from board where subject like '%친%';
